// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-3gWXekEd-SMGQfQfxrGaahUzCDmTMKk',
    appId: '1:143696580444:android:4b162668188c6fb8073b99',
    messagingSenderId: '143696580444',
    projectId: 'edubridge-e673c',
    storageBucket: 'edubridge-e673c.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKRwNdaw0ITV2SAbm4s_3eR4q-nymbyTo',
    appId: '1:143696580444:ios:7a77b495ec29f910073b99',
    messagingSenderId: '143696580444',
    projectId: 'edubridge-e673c',
    storageBucket: 'edubridge-e673c.firebasestorage.app',
    iosBundleId: 'mn.ariunboldtsedenbal.edubridge',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKRwNdaw0ITV2SAbm4s_3eR4q-nymbyTo',
    appId: '1:143696580444:ios:d1c03fc8cce0bd90073b99',
    messagingSenderId: '143696580444',
    projectId: 'edubridge-e673c',
    storageBucket: 'edubridge-e673c.firebasestorage.app',
    iosBundleId: 'com.example.edubridge',
  );
}
